name: imgbuild
on:
  push:
    branches:
      - main
      - 'AddBuilder'
env:
  MYNAME: hinoshiba
jobs:
    imgbuild:
      runs-on: ubuntu-latest
      steps:
      - name: Get current week-id
        id: date
        run: echo "::set-output name=weekid::$(date +'%Y%U')"
      - name: Checkout from repository.
        uses: actions/checkout@v2
      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Hub.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/workbench
          push: true
          tags: |
            workbench:latest
            workbench:${{ steps.date.outputs.weekid }}
