name: imgbuild
on:
  push:
    branches:
      - main
      - 'AddBuilder'
jobs:
    imgbuild:
      runs-on: ubuntu-latest
      steps:
      - name: Move to CURDIR
        run: cd dockerfiles/workbench
      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v2
