name: imgbuild
on:
  schedule:
    - cron: "0 0 * * 6"
  push:
    branches:
      - master
      - UpdateActions
env:
  MYNAME: hinoshiba
jobs:
    setup:
      runs-on: ubuntu-latest
      steps:
      - name: Get current week-id
        id: date
        run: echo "weekid=$(date +'%Y%U')" >> $GITHUB_OUTPUT
      - name: Checkout from repository.
        uses: actions/checkout@v2
      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    imgbuild-workbehcn:
      runs-on: ubuntu-latest
      needs: setup
      steps:
      - name: Build and Push to Docker Hub for workbench.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/workbench
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/workbench:latest
            ${{ env.MYNAME}}/workbench:${{ needs.setup.outputs.weekid }}

    imgbuild-golang:
      runs-on: ubuntu-latest
      needs: setup
      steps:
      - name: Build and Push to Docker Hub for golang.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/golang
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/golang:latest
            ${{ env.MYNAME}}/golang:${{ needs.setup.outputs.weekid }}

    imgbuild-python3:
      runs-on: ubuntu-latest
      needs: setup
      steps:
      - name: Build and Push to Docker Hub for python3.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/python3
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/python3:latest
            ${{ env.MYNAME}}/python3:${{ needs.setup.outputs.weekid }}

    imgbuild-research:
      runs-on: ubuntu-latest
      needs: setup
      steps:
      - name: Build and Push to Docker Hub for research.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/research
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/research:latest
            ${{ env.MYNAME}}/research:${{ needs.setup.outputs.weekid }}

    imgbuild-tor:
      runs-on: ubuntu-latest
      needs: setup
      steps:
      - name: Build and Push to Docker Hub for tor.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/tor
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/tor:latest
            ${{ env.MYNAME}}/tor:${{ needs.setup.outputs.weekid }}
