name: imgbuild
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 毎週日曜日に実行
env:
  MYNAME: hinoshiba
jobs:
    imgbuild:
      runs-on: ubuntu-latest
      steps:
      - name: Get current week-id
        id: date
        run: echo "::set-output name=weekid::$(date +'%Y%U')"
      - name: Checkout from repository.
        uses: actions/checkout@v2
      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub for workbench.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/workbench
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/workbench:latest
            ${{ env.MYNAME}}/workbench:${{ steps.date.outputs.weekid }}

      - name: Build and Push to Docker Hub for golang.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/golang
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/workbench:latest
            ${{ env.MYNAME}}/workbench:${{ steps.date.outputs.weekid }}

      - name: Build and Push to Docker Hub for python3.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/python3
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/workbench:latest
            ${{ env.MYNAME}}/workbench:${{ steps.date.outputs.weekid }}

      - name: Build and Push to Docker Hub for research.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/research
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/workbench:latest
            ${{ env.MYNAME}}/workbench:${{ steps.date.outputs.weekid }}

      - name: Build and Push to Docker Hub for tor.
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/tor
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.MYNAME}}/workbench:latest
            ${{ env.MYNAME}}/workbench:${{ steps.date.outputs.weekid }}
