name: life check
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
      - AddActions4life
jobs:
    check:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          include:
            - PRODUCT: golang
              VERSION: 1.20
            - PRODUCT: python
              VERSION: 3.11
      steps:
      - name: Checkout from repository.
        uses: actions/checkout@v2
      - name: Check a latest version.
        id: latest_env
        run: |
            curl -L -s --request GET --url https://endoflife.date/api/${{matrix.PRODUCT}}/${{matrix.VERSION}}.json --header 'Accept: application/json' > /tmp/version.json
            echo "Version=$(cat /tmp/version.json | jq '.latest')" >> "$GITHUB_OUTPUT"
            echo "IsEol=$(cat /tmp/version.json | jq '.eol')" >> "$GITHUB_OUTPUT"
      - name: Make a latest dockerfile.
        id: diff_check
        run: |
            cp dockerfiles/${{matrix.PRODUCT}}/Dockerfile /tmp/Dockerfile_bk
            version=${{steps.latest_env.outputs.Version}}; sed -i 's/${{matrix.PRODUCT}}:[0-9.]*\s/${{matrix.PRODUCT}}:'${version}' /' dockerfiles/${{matrix.PRODUCT}}/Dockerfile
            diff -q /tmp/Dockerfile_bk dockerfiles/${{matrix.PRODUCT}}/Dockerfile
        continue-on-error: true
      - name: CreatePR
        uses: peter-evans/create-pull-request@v5
        with:
          title: '[NewVersion] ${{matrix.PRODUCT}}/${{steps.latest_env.outputs.Version}}'
          body: |
            ${{matrix.PRODUCT}}/${{steps.latest_env.outputs.Version}} is detected!
            detail >> https://endoflife.date/${{matrix.PRODUCT}}
          commit-message: "by life_pr.yml"
        if: steps.diff_check.outcome == 'failure'
      - name: checkoel
        id: not_eol
        run: test "false" == "${{steps.env.outputs.IsEol}}" && exit 1
        continue-on-error: true
      - name: CreateIssueTemplate
        run: |
            mkdir .tmp
            echo "---" >> .tmp/issue.md
            echo "title: [EOL] ${{matrix.PRODUCT}}/${{matrix.VERSION}}" >> .tmp/issue.md
            echo "labels: ['EOL']" >> .tmp/issue.md
            echo "assignees: hinoshiba" >> .tmp/issue.md
            echo "---" >> .tmp/issue.md
            echo "${{matrix.PRODUCT}}/${{matrix.VERSION}} is EOL." >> .tmp/issue.md
            echo "detail > https://endoflife.date/${{matrix.PRODUCT}}" >> .tmp/issue.md
            cat .tmp/issue.md
        if: steps.not_eol.outcome == 'failure'
      - name: CreateIssue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          update_existing: true
          search_existing: all
          filename: .tmp/issue.md
        if: steps.not_eol.outcome == 'failure'
